### ISSUE TITLE
Illegal Reflective access operation in JDK 9+

### ISSUE THREAD

**Issue by carimura** [HubSpot/slack-client#100]
Hi, thanks for the easy-to-use client!

The following warnings show up in JDK 9+:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hubspot.horizon.shaded.org.jboss.netty.util.internal.ByteBufferUtil (file:/usr/share/jimage/jimage.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.hubspot.horizon.shaded.org.jboss.netty.util.internal.ByteBufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Running with `--illegal-access=debug` results in:
```
WARNING: Illegal reflective access by com.hubspot.horizon.shaded.org.jboss.netty.util.internal.ByteBufferUtil (file:/usr/share/jimage/jimage.jar) to method java.nio.DirectByteBuffer.cleaner()
	at com.hubspot.horizon.shaded.org.jboss.netty.util.internal.ByteBufferUtil.<clinit>(ByteBufferUtil.java:35)
	at com.hubspot.horizon.shaded.org.jboss.netty.channel.socket.nio.SocketReceiveBufferAllocator.newBuffer(SocketReceiveBufferAllocator.java:62)
	at com.hubspot.horizon.shaded.org.jboss.netty.channel.socket.nio.SocketReceiveBufferAllocator.get(SocketReceiveBufferAllocator.java:44)
	at com.hubspot.horizon.shaded.org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:62)
	at com.hubspot.horizon.shaded.org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at com.hubspot.horizon.shaded.org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at com.hubspot.horizon.shaded.org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at com.hubspot.horizon.shaded.org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at com.hubspot.horizon.shaded.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at com.hubspot.horizon.shaded.org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

JDK 11 and 12 should still work with warnings, but future releases will change the default runtime mode to `deny`.

More info here: http://openjdk.java.net/jeps/261#Relaxed-strong-encapsulation

**Comment by jxbadam** [comment]
This problem appears to be due to the jboss netty dependency.

This can be resolved by either removing that dependency, or updating to a later version of said dependency where the dependency maintainers have fixed this issue.

**Comment by szabowexler** [comment]
Thanks for letting us know. It'll take a bit, but we'll look into upgrading netty to avoid having an incompatibility with future JDKs.
